# Data Loading, Storage,

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

## Reading and Writing Data in Text Format

In [3]:
!cat examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [4]:
df = pd.read_csv('examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
pd.read_table('examples/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
!cat examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [8]:
pd.read_csv('examples/ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [7]:
pd.read_csv('examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [9]:

pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [10]:
names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('examples/ex2.csv', names=names, index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [12]:
!cat examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [13]:

parsed = pd.read_csv('examples/csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [14]:
list(open('examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [15]:
result = pd.read_table('examples/ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [17]:
!cat examples/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [18]:

pd.read_csv('examples/ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [19]:
!cat examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [20]:

result = pd.read_csv('examples/ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [21]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [24]:
result = pd.read_csv('examples/ex5.csv', na_values=['null'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [25]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv('examples/ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

### Reading Text Files in Pieces

In [37]:
pd.options.display.max_rows = 5

In [38]:
result = pd.read_csv('examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
...        ...       ...       ...       ...  ..
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [39]:
pd.read_csv('examples/ex6.csv', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [40]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
chunker

In [43]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)

tot = pd.Series([])
for index, piece in enumerate(chunker):
    if index==0:
        print(type(piece))
        print(piece)
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

<class 'pandas.core.frame.DataFrame'>
          one       two     three      four key
0    0.467976 -0.038649 -0.295344 -1.824726   L
1   -0.358893  1.404453  0.704965 -0.200638   B
..        ...       ...       ...       ...  ..
998 -0.362559  0.598894 -1.843201  0.887292   W
999 -0.096376 -1.012999 -0.657431 -0.573315   K

[1000 rows x 5 columns]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  This is separate from the ipykernel package so we can avoid doing imports until

In [42]:
tot[:10]

E    368.0
X    364.0
     ...
K    334.0
H    330.0
Length: 10, dtype: float64

### Writing Data to Text Format

In [44]:
data = pd.read_csv('examples/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [45]:
data.to_csv('examples/out.csv')
!cat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [46]:
import sys
sys.stdout

In [47]:

data.to_csv(sys.stdout, sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [48]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [49]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [50]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [52]:
dates = pd.date_range('1/1/2000', periods=7)
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [53]:
ts = pd.Series(np.arange(7), index=dates)
ts

2000-01-01    0
2000-01-02    1
             ..
2000-01-06    5
2000-01-07    6
Freq: D, Length: 7, dtype: int64

In [54]:
ts.to_csv('examples/tseries.csv')
!cat examples/tseries.csv

,0
2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

### Working with Delimited Formats

In [55]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [57]:
import csv
f = open('examples/ex7.csv')

reader = csv.reader(f)
reader

In [58]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [60]:
with open('examples/ex7.csv') as f:
    lines = list(csv.reader(f))
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [62]:
header, values = lines[0], lines[1:]

In [63]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

reader = csv.reader(f, dialect=my_dialect)

reader = csv.reader(f, delimiter='|')

with open('mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))

### JSON Data

In [64]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [66]:
import json
result = json.loads(obj)
result, type(result)

({'name': 'Wes',
  'places_lived': ['United States', 'Spain', 'Germany'],
  'pet': None,
  'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
   {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]},
 dict)

In [67]:
asjson = json.dumps(result)

In [69]:
asjson, type(asjson)

('{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}',
 str)

In [70]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   30
1  Katie   38

In [72]:
!cat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [73]:
data = pd.read_json('examples/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [74]:
print(data.to_json())
print(data.to_json(orient='records'))

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}
[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

### XML and HTML: Web Scraping

conda install lxml
pip install beautifulsoup4 html5lib

In [75]:
tables = pd.read_html('examples/fdic_failed_bank_list.html')
len(tables)
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [76]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps.dt.year.value_counts()

2010    157
2009    140
       ...
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

#### Parsing XML with lxml.objectify

<INDICATOR>
  <INDICATOR_SEQ>373889</INDICATOR_SEQ>
  <PARENT_SEQ></PARENT_SEQ>
  <AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
  <INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
  <DESCRIPTION>Percent of the time that escalators are operational
  systemwide. The availability rate is based on physical observations performed
  the morning of regular business days only. This is a new indicator the agency
  began reporting in 2009.</DESCRIPTION>
  <PERIOD_YEAR>2011</PERIOD_YEAR>
  <PERIOD_MONTH>12</PERIOD_MONTH>
  <CATEGORY>Service Indicators</CATEGORY>
  <FREQUENCY>M</FREQUENCY>
  <DESIRED_CHANGE>U</DESIRED_CHANGE>
  <INDICATOR_UNIT>%</INDICATOR_UNIT>
  <DECIMAL_PLACES>1</DECIMAL_PLACES>
  <YTD_TARGET>97.00</YTD_TARGET>
  <YTD_ACTUAL></YTD_ACTUAL>
  <MONTHLY_TARGET>97.00</MONTHLY_TARGET>
  <MONTHLY_ACTUAL></MONTHLY_ACTUAL>
</INDICATOR>

In [79]:
from lxml import objectify

path = 'datasets/mta_perf/Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()

UnicodeDecodeError: ignored

In [ ]:
data = []

skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ',
               'DESIRED_CHANGE', 'DECIMAL_PLACES']

for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval
    data.append(el_data)

In [ ]:
perf = pd.DataFrame(data)
perf.head()

In [ ]:
from io import StringIO
tag = '<a href="http://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()

In [ ]:
root
root.get('href')
root.text

## Binary Data Formats

In [80]:
frame = pd.read_csv('examples/ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [81]:

frame.to_pickle('examples/frame_pickle')

In [82]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [83]:
!rm examples/frame_pickle

### Using HDF5 Format

In [84]:
frame = pd.DataFrame({'a': np.random.randn(100)})
frame

           a
0  -0.204708
1   0.478943
..       ...
98  0.584970
99  0.152677

[100 rows x 1 columns]

In [90]:
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [91]:
store['obj1']

           a
0  -0.204708
1   0.478943
..       ...
98  0.584970
99  0.152677

[100 rows x 1 columns]

In [92]:
store.put('obj2', frame, format='table')

In [93]:
store.select('obj2', where=['index >= 10 and index <= 15'])

           a
10  1.007189
11 -1.296221
..       ...
14  1.352917
15  0.886429

[6 rows x 1 columns]

In [94]:
store.close()

In [95]:
frame.to_hdf('mydata.h5', 'obj3', format='table')
pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

          a
0 -0.204708
1  0.478943
2 -0.519439
3 -0.555730
4  1.965781

In [97]:
import os

In [98]:
os.remove('mydata.h5')

*이탤릭체 텍스트*### Reading Microsoft Excel Files

In [99]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')

In [103]:
for sheetname in xlsx.sheet_names:
    df = pd.read_excel(xlsx, sheetname)

['Sheet1']

In [100]:
pd.read_excel(xlsx, 'Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [101]:
frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1')
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [ ]:
writer = pd.ExcelWriter('examples/ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

In [ ]:
frame.to_excel('examples/ex2.xlsx')

In [ ]:
!rm examples/ex2.xlsx

## Interacting with Web APIs

In [104]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [105]:
data = resp.json()
data[0]['title']

"BUG: 'Series.to_numpy(dtype=, na_value=)' behaves differently with 'pd.NA' and 'np.nan'"

In [106]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48951',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48951/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48951/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48951/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/48951',
  'id': 1397146905,
  'node_id': 'I_kwDOAA0YD85TRsUZ',
  'number': 48951,
  'title': "BUG: 'Series.to_numpy(dtype=, na_value=)' behaves differently with 'pd.NA' and 'np.nan'",
  'user': {'login': 'bbassett-tibco',
   'id': 81381063,
   'node_id': 'MDQ6VXNlcjgxMzgxMDYz',
   'avatar_url': 'https://avatars.githubusercontent.com/u/81381063?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/bbassett-tibco',
   'html_url': 'https://github.com/bbassett-tibco',
   'followers_url': 'https://api.github.com/users/bbassett-tibco/followers',
   'following_url': 'https://api.github.com/users/bbassett-tibco/following{/other_user}',
   'gists_url': 'https://api.github.com/users/bbassett-tibco/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/bbassett-tibco/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/bbassett-tibco/subscriptions',
   'organizations_url': 'https://api.github.com/users/bbassett-tibco/orgs',
   'repos_url': 'https://api.github.com/users/bbassett-tibco/repos',
   'events_url': 'https://api.github.com/users/bbassett-tibco/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/bbassett-tibco/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1817503692,
    'node_id': 'MDU6TGFiZWwxODE3NTAzNjky',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/NA%20-%20MaskedArrays',
    'name': 'NA - MaskedArrays',
    'color': '8cc645',
    'default': False,
    'description': 'Related to pd.NA and nullable extension arrays'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 3,
  'created_at': '2022-10-05T03:27:00Z',
  'updated_at': '2022-10-05T08:26:43Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\nimport numpy as np\r\n\r\nx1 = pd.Series([1, 2, None, 4])\r\nx2 = pd.Series([1, 2, np.nan, 4])\r\nx3 = pd.Series([1, 2, pd.NA, 4])\r\n\r\nprint(x1.to_numpy(\'int32\', na_value=0))\r\n# [1 2 0 4]\r\n\r\nprint(x2.to_numpy(\'int32\', na_value=0))\r\n# [1 2 0 4]\r\n\r\nprint(x3.to_numpy(\'int32\', na_value=0))\r\n# Traceback (most recent call last):\r\n#   File "<input>", line 14, in <module>\r\n#     print(x3.to_numpy(\'int32\', na_value=0))\r\n#   File "C:\\src\\venv\\w310\\lib\\site-packages\\pandas\\core\\base.py", line 535, in to_numpy\r\n#     result = np.asarray(self._values, dtype=dtype)\r\n# TypeError: int() argument must be a string, a bytes-like object or a real number, not \'NAType\'\r\n\r\nprint(x3.to_numpy(\'float64\', na_value=0))\r\n# Traceback (most recent call last):\r\n#   File "<input>", line 22, in <module>\r\n#     print(x3.to_numpy(\'float64\', na_value=0))\r\n#   File "C:\\src\\venv\\w310\\lib\\site-packages\\pandas\\core\\base.py", line 535, in to_numpy\r\n#     result = np.asarray(self._values, dtype=dtype)\r\n# TypeError: float() argument must be a string or a real number, not \'NAType\'\n```\n\n\n### Issue Description\n\nIt appears that a Series that has a missing value that was created using either `None` or `np.nan` can be replaced by using `Series.to_numpy(dtype=, na_value=)`, but one created with `pd.NA` fails with a raised exception (both arguments must be specified to trigger the behavior).\n\n### Expected Behavior\n\nIt is expected that since all three values (`None`, `np.nan`, and `pd.NA`) all represent missing values, that all three should behave the same.  For the above reproducible example, the print statements should all report `[1 2 0 4]` (or `[1. 2. 0. 4.]` for the fourth \'float64\' case).\n\n### Installed Versions\n\n<details>\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763\r\npython           : 3.10.6.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19043\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\npandas           : 1.5.0\r\nnumpy            : 1.23.3\r\npytz             : 2022.2.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 65.3.0\r\npip              : 22.2.2\r\nCython           : 0.29.32\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.9.1\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nbrotli           : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.6.0\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : NoneReplace this line with the output of pd.show_versions()\r\n\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48951/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48951/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48950',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48950/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48950/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48950/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/48950',
  'id': 1397017165,
  'node_id': 'I_kwDOAA0YD85TRMpN',
  'number': 48950,
  'title': 'BUG: Window.Rolling.std changes significantly',
  'user': {'login': 'MichalRIcar',
   'id': 62614119,
   'node_id': 'MDQ6VXNlcjYyNjE0MTE5',
   'avatar_url': 'https://avatars.githubusercontent.com/u/62614119?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MichalRIcar',
   'html_url': 'https://github.com/MichalRIcar',
   'followers_url': 'https://api.github.com/users/MichalRIcar/followers',
   'following_url': 'https://api.github.com/users/MichalRIcar/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MichalRIcar/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MichalRIcar/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MichalRIcar/subscriptions',
   'organizations_url': 'https://api.github.com/users/MichalRIcar/orgs',
   'repos_url': 'https://api.github.com/users/MichalRIcar/repos',
   'events_url': 'https://api.github.com/users/MichalRIcar/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MichalRIcar/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-05T00:43:00Z',
  'updated_at': '2022-10-05T00:57:55Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nfrom pandas import Series as pSe\r\nimport numpy  as np\r\n\r\n# DATA\r\nmu = 9e-06\r\nsi = 5e-06\r\n\r\nT0 = [100 for i in range(10)]\r\nT1 = list(np.random.normal(mu, si, 8000))\r\n\r\nt = 15\r\n\r\n# STD1\r\nT = pSe(T0 + T1)\r\nr1 = T.rolling(t).std().iloc[-1]\r\n\r\n# STD2\r\nT = pSe(T1)\r\nr2 = T.rolling(t).std().iloc[-1]\r\n\r\n# DIFF (%)\r\n(r2/r1-1)*100\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nHello,\r\n\r\nI have come to a problematic behavior of rolling window std  - and only std as mean works OK always - in the case of the real world data set. \r\nData of length 9000 OBS where only the very first 10 values have a different magnitude and the rest of the data is oscillating around mean, std of its distribution. \r\n\r\nHowever, we have found a problematic behavior as for the last observations of the data set, the rolling window std of length t = 15 was 2 times higher compared to the same data set when just the very first OBS was removed (only 1 obs was removed from the very beginning of the data - 8999 values were just same). \r\n\r\nIn other words, in the case of the real-world data, the rolling std produced a 2xhigher result at the very end of the data (9000th obs) compared to the very same data set where only the very first observation was removed. \r\n\r\nI have tried to reproduce it with artificial data, and I was able to get a result where the difference is 0.5-15% (variance is coming from randomly generated data) as shown below.\r\n\r\n![image](https://user-images.githubusercontent.com/62614119/193956112-50bbc9c9-b73e-4347-91c2-6292fc5e5cea.png)\r\n\r\n\r\n### Expected Behavior\r\n\r\nRolling window std with given lag (e.g. 15) should be consistent as the window.mean is → produces the same results regardless of little and far away (in the data sense) changes.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6\r\npython           : 3.9.7.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19043\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.4.3\r\nnumpy            : 1.20.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\nsetuptools       : 58.0.4\r\npip              : 21.2.4\r\nCython           : 0.29.24\r\npytest           : 6.2.4\r\nhypothesis       : None\r\nsphinx           : 4.2.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.1\r\nlxml.etree       : 4.6.3\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.3\r\nIPython          : 7.29.0\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : 1.3.2\r\nbrotli           : \r\nfastparquet      : None\r\nfsspec           : 2021.10.1\r\ngcsfs            : None\r\nmarkupsafe       : 1.1.1\r\nmatplotlib       : 3.5.2\r\nnumba            : 0.54.1\r\nnumexpr          : 2.7.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsnappy           : None\r\nsqlalchemy       : 1.4.22\r\ntables           : 3.6.1\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : 1.3.0\r\nzstandard        : None\r\n</details>\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48950/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48950/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48949',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48949/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48949/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48949/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/48949',
  'id': 1397011293,
  'node_id': 'I_kwDOAA0YD85TRLNd',
  'number': 48949,
  'title': 'ENH: pre-commit check for setup.cfg options.extras_require',
  'user': {'login': 'JMBurley',
   'id': 23153616,
   'node_id': 'MDQ6VXNlcjIzMTUzNjE2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/23153616?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/JMBurley',
   'html_url': 'https://github.com/JMBurley',
   'followers_url': 'https://api.github.com/users/JMBurley/followers',
   'following_url': 'https://api.github.com/users/JMBurley/following{/other_user}',
   'gists_url': 'https://api.github.com/users/JMBurley/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/JMBurley/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/JMBurley/subscriptions',
   'organizations_url': 'https://api.github.com/users/JMBurley/orgs',
   'repos_url': 'https://api.github.com/users/JMBurley/repos',
   'events_url': 'https://api.github.com/users/JMBurley/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/JMBurley/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-05T00:34:31Z',
  'updated_at': '2022-10-05T00:34:31Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': '### Feature Type\n\n- [X] Adding new functionality to pandas\n\n- [ ] Changing existing functionality in pandas\n\n- [ ] Removing existing functionality in pandas\n\n\n### Problem Description\n\nAfter #47336 added optional_extras, we do not have a programmatic check that versions are aligned across the all places they are specified in pandas.\r\n\r\n@JMBurley & @mroeschke  active in prior thread.\n\n### Feature Description\n\nA pre-commit check that ensure that the min version in setup.cfg are aligned with other areas we specify min version (would mean augmenting scripts/validate_min_versions_in_sync.py)\n\n### Alternative Solutions\n\nN/A.  Simplest to extend existing actions to cover new usage.\n\n### Additional Context\n\n_No response_',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48949/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48949/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48948',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48948/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48948/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/48948/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/48948',
  'id': 1397004757,
  'node_id': 'PR_kwDOAA0YD85ALGkh',
  'number': 48948,
  'title': 'STYLE: Add code check to avoid returning Exceptions instead of raising',
  'user': {'login': 'mroeschke',
   'id': 10647082,
   'node_id': 'MDQ6VXNlcjEwNjQ3MDgy',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mroeschke',
   'html_url': 'https://github.com/mroeschke',
   'followers_url': 'https://api.github.com/users/mroeschke/followers',
   'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions',
   'organizations_url': 'https://api.github.com/users/mroeschke/orgs',
   'repos_url': 'https://api.github.com/users/mroeschke/repos',
   'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mroeschke/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 106935113,
    'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Code%20Style',
    'name': 'Code Style',
    'color': 'eb6420',
    'default': False,
    'description': 'Code style, linting, code_checks'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-10-05T00:24:31Z',
  'updated_at': '2022-10-05T00:24:31Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/48948',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/48948',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/48948.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/48948.patch',
   'merged_at': None},

In [107]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues

,number,title,labels,state
0,48951,"BUG: 'Series.to_numpy(dtype=, na_value=)' beha...","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
1,48950,BUG: Window.Rolling.std changes significantly,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
...,...,...,...,...
28,48918,"API: Timedelta constructor pytimedelta, Tick p...","[{'id': 49597148, 'node_id': 'MDU6TGFiZWw0OTU5...",open
29,48916,"DOC: per docs, ""margins"" parameter returns row...","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open

In [110]:
pd.DataFrame(issues['labels'].values[0])

,id,node_id,url,name,color,default,description
0,76811,MDU6TGFiZWw3NjgxMQ==,https://api.github.com/repos/pandas-dev/pandas...,Bug,e10c02,False,None
1,1817503692,MDU6TGFiZWwxODE3NTAzNjky,https://api.github.com/repos/pandas-dev/pandas...,NA - MaskedArrays,8cc645,False,Related to pd.NA and nullable extension arrays

## Interacting with Databases

In [111]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata.sqlite')
con.execute(query)
con.commit()

In [112]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [113]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [115]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [118]:
import sqlalchemy as sqla
db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

OperationalError: ignored

In [117]:
!rm mydata.sqlite

## Conclusion